### ISSUE TITLE
locker_uri problem with port specification

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry-community/locker-resource#1]
Problem
--------

when i try to specify the locker resource in the pipeline.yml like this:
```
resources:
- name: myLock
  type: locker
  source:
    locker_uri: http://10.10.10.10:8910
    username: test
    password: test
    lock_name: myLock
```

i receive this error message:
`parse error: Invalid numeric literal at line 2, column 0`

What causes the bug?
---------------------

The yaml is invalid cause of the ":" inside the `locker_uri` string.
I already tried to specify it like this:
- `locker_uri: "http://10.10.10.10:8910"`
- `locker_uri: 'http://10.10.10.10:8910'`

Neither of these strings worked.

Suggestion
-----------

Introduction of a port source variable for the resource rather than passing the port number along with the `locker_uri` string

best,
